services:
  db:
    image: mariadb:11.7.2-noble
    environment:
      - TZ=Europe/Berlin
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=testDB
      - MARIADB_PASSWORD=${DB_USER_PASSWORD}
      - MARIADB_USER=dev
    ports:
      - 3306:3306
    restart: always
    volumes:
      - lp-db-vol:/var/lib/mysql
  pma:
    image: phpmyadmin:5.2.1
    environment:
      - TZ=Europe/Berlin
      - PMA_HOST=db
      - UPLOAD_LIMIT=20M
      - MAX_EXECUTION_TIME=3600
    depends_on:
      - db
    restart: always
    ports:
      - 6080:80

volumes:
  lp-db-vol:
      